### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by Meta-Learn-ApS** [tjarvstrand/flutter_timezone#10]
When i build it it says:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_timezone:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 1.8) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by tjarvstrand** [comment]
Hm, unfortunately I'm not familiar enough with the Android Gradle Plugin to know what might be wrong based on this information alone. Do you have any clue what might be going on?

**Comment by tjarvstrand** [comment]
@Meta-Learn-ApS 

Could you try it wouth only the `JavaVersion.VERSION_1_8`-options, without the `kotlinOptions`?

**Comment by luandnguyen** [comment]
@tjarvstrand The error above happens because, in Android Studio Flamingo, the Android Gradle Plugin is now version 8. This new AS version packages Java 17 as the default JDK. I'll submit a PR with a fix.

**Comment by luandnguyen** [comment]
When upgrading Android Studio, the IDE bundles a different default JDK version. In my case, I'm using AS Flamingo which comes with JDK 17 and it recommends using Android Gradle Plugin version 8.0, which requires JDK 17 to run. In this project, I see that you are still using AGP 4.2 which is completely fine; we just need to define a compatible Kotlin JVM target so that newer versions of AS do not use the bundled JDK as the target. You already define the Java versions via `java` block; this only applies to any codes written in Java in the project. You will need the kotlin block for kotlin codes.

I hope this all make sense 😓 Android build setup is not particularly easy to understand. Here's an explanation: https://stefma.medium.com/sourcecompatibility-targetcompatibility-and-jvm-toolchains-in-gradle-explained-d2c17c8cff7c

Do you want me to submit a PR for the `kotlinOptions` change, or can you add it on your side? It will just look like what @Meta-Learn-ApS posted above.

```
android {
    ...
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
}
```

**Comment by tjarvstrand** [comment]
Yeah, I think that makes sense. Thanks for taking the time to look into it and explaining. I can make the change but I'm a bit busy at the moment so if you are keen and have time to spare, a PR would be briliant!

**Comment by luandnguyen** [comment]
@tjarvstrand I can't seem to push and make a PR to your repo. Do I need permission?

**Comment by luandnguyen** [comment]
Thank you. PR is created!

**Comment by luandnguyen** [comment]
PR is merged. Maybe we can close this ticket?

**Comment by tjarvstrand** [comment]
Sure! :)
