### ISSUE TITLE
[iOS] Are there any plans to add Privacy Manifests? 

### ISSUE THREAD

**Issue by StatusCode200** [tjarvstrand/flutter_timezone#23]
Apple recently announced that starting in Spring 2024, apps will be required to include more privacy-related reasoning for "third-party SDKs." This includes providing details in privacy manifests about data use by these SDKs. You can read more about this requirement on the Apple Developer website: [Describing Data Use in Privacy Manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc)

Many popular Flutter plugins, such as shared_preferences, have already implemented these manifests. You can see an example of such a manifest in the shared_preferences plugin here: [PrivacyInfo.xcprivacy](https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences_foundation/darwin/Resources/PrivacyInfo.xcprivacy)

Given these upcoming requirements, it's important to note that even libraries that do not collect privacy-policy-relevant information may need to include an empty PrivacyInfo.xcprivacy file to avoid potential rejection.

Thank you for your attention to this matter.

**Comment by tjarvstrand** [comment]
Thank you for bringing this to my attention. I will look into it!

**Comment by jsch-adt** [comment]
Any chance this will be added by May 1?

**Comment by tjarvstrand** [comment]
I'm currently absolutely swamped and I'm not sure if I'll have time to look into this before then.

**Comment by StatusCode200** [comment]
@tjarvstrand 
Sorry for the late reply.

I share this information from Apple.
https://developer.apple.com/news/?id=3d8a9yyh

A discussion was held and we will share this as well.
https://github.com/flutter/flutter/issues/131940

I believe that third-party plugins that include iOS code should be supported as they tend to be supported across the board.
I would appreciate it if you could please ...

Sorry, translated English.

**Comment by martin-headspace** [comment]
Based on my reading of Apple's announcement, it sounds to me like adding third-party privacy manifests is only mandatory for a very specific number of third-party libraries.  (see https://developer.apple.com/support/third-party-SDK-requirements/)

I am, however, exercising the same caution the Flutter team did. Since this list is non-exhaustive, it feels like in the future these requirements could be extended to other libraries. (see https://github.com/flutter/flutter/issues/131940)

In that case, I believe it's fair to include an empty privacy manifest for now and modify it in the future if Apple changes their requirements for them. 

I've opened a PR tackling just that

https://github.com/tjarvstrand/flutter_timezone/pull/27

**Comment by tjarvstrand** [comment]
Hi @martin-headspace 

You closed the PR mentioned above so I'll close this for now as well. I haven't been able to find anything in Apple's documentation indicating that this plugin should include a privacy file. I also haven't heard any indications that users are encountering any such issues with flutter_timezone.

Feel free to reopen if you think this is important.
