### ISSUE TITLE
the procedure entry point getuserdefaultgeoname could not be located in the dynamic link library

### ISSUE THREAD

**Issue by lavishmanghnani2** [tjarvstrand/flutter_timezone#39]

**Comment by lavishmanghnani2** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/6fc18318-7bc2-4153-9f16-bf27a31a8929)


getting this error in some pc and in other its perfectly working

**Comment by lavishmanghnani2** [comment]
@domyd  on this 

![image](https://github.com/user-attachments/assets/95a42d8d-faee-464d-96f0-d609796ed2de)

**Comment by domyd** [comment]
Flutter isn't even technically supported on Server 2012 R2, and I'm guessing the Version of Server 2016 is very old (even though the function should be supported on all of them according to the docs).

Here's the thing: It's really difficult to get an IANA time zone identifier on Windows 10 older than 1709—i.e. pre-2017 Windows—since the APIs just aren't there (`ucal_getTimeZoneIDForWindowsID` isn't available either). We would basically have to do what NodaTime does and map between Windows and IANA identifiers by ourselves using the Unicode datasets. I sadly feel like that's out of scope for this package; at least I don't really have the time to make that happen.

@tjarvstrand We should probably add a disclaimer that Windows is only supported from Windows 10 Version 1709 and later.
